### ISSUE TITLE
Difference between frame2time and upbd file

### ISSUE THREAD

**Issue by PolarisHsu** [doc-doc/NExT-GQA#4]
Hi there! Thanks for your great work.
What's the difference between frame2time_{split} and upbd_{split}? It looks exactly the same.

**Comment by doc-doc** [comment]
Hi, yes, they are the same.

**Comment by PolarisHsu** [comment]
> Hi, yes, they are the same.

Thanks for your timely reply. In addition, could you please provide the file 'train_gpt4_sub.json'?

**Comment by doc-doc** [comment]
Hi, I have uploaded it into the datasets folder.

**Comment by PolarisHsu** [comment]
Thanks a lot!
